from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import uvicorn

app = FastAPI(title="Auto Reviewer API", version="0.1.0")

# Add CORS middleware to allow frontend to communicate with backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ReviewRequest(BaseModel):
    content: str

class ReviewResponse(BaseModel):
    reviewed_content: str
    message: Optional[str] = None

@app.get("/")
async def root():
    return {"message": "Auto Reviewer API is running!"}

@app.get("/health")
async def health_check():
    return {"status": "healthy"}

@app.post("/api/review", response_model=ReviewResponse)
async def review_content(request: ReviewRequest):
    """
    Mock endpoint that simulates content review.
    In a real implementation, this would use the GCP class to process the content.
    """
    try:
        # Mock review logic - in real implementation, this would use the GCP class
        content = request.content
        
        # Simple mock transformation
        reviewed_content = f"""# Reviewed Content

## Original Content Summary
The original content was {len(content)} characters long.

## Review Notes
This is a mock review response. In the actual implementation, this would be processed by the GCP AI model.

## Suggested Improvements
- Add more structure to the content
- Include specific examples
- Consider adding a conclusion

## Revised Content
{content}

---
*This review was generated by the Auto Reviewer system.*
"""
        
        return ReviewResponse(
            reviewed_content=reviewed_content,
            message="Content reviewed successfully"
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing content: {str(e)}")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
